# Generated by Django 2.2.4 on 2023-04-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
