# Generated by Django 2.2.4 on 2023-04-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0004_auto_20230404_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
