# Generated by Django 2.2.4 on 2023-04-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0005_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_order',
            field=models.FloatField(default=1),
        ),
    ]
